# Site Settings
name: Tushar Sharma
description: DedSec has given you the truth , do what you will
baseurl: ""
url : "https://tusharxsharma.github.io/Portfolio"

# Blog Settings
theme_settings :
  title : TusharSharma -Algorithm
  favicon : assets/faviconn.ico

  # Profile Settings
  profile :
    image : assets/img/dp.png
    username : Tushar Sharma
    description : Do What You Will.
    experience :
      - start : August 18
        end : Never Ending
        experience : BCA
    skills : 
      - skill : HTML5 & CSS
        value : 50 # Percent value
      - skill : Gaming
        value : 95
      - skill : C++
        value : 70
      - skill : Java
        value : 50
      - skill : C
        value : 60

  # Icons
  icons :
    email:  tusharsharmavj@gmail.com
    linkedin: https://www.linkedin.com/in/tusharsharmavj/ # Full URL 
    github: tusharxsharma
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: 
    youtube:
    facebook: 
    instagram: jaggerxr

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
